# Generated by Django 5.0.1 on 2024-01-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tweet_date_alter_tweet_photo_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tweet_pic'),
        ),
    ]
