# Generated by Django 5.0.1 on 2024-02-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_profile_email_remove_profile_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user',
            new_name='author',
        ),
    ]
