# Generated by Django 5.0.1 on 2024-02-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_following_user_id_userfollowing_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='category',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Politica', 'Politica'), ('Cinema', 'Cinema'), ('Musica', 'Musica'), ('Viaggi', 'Viaggi'), ('Tecnologia', 'Tecnologia'), ('Cucina', 'Cucina'), ('Arte', 'Arte'), ('Fotografia', 'Fotografia')], default='Tecnologia', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='main.profile'),
        ),
    ]
